# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bellman-bd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bellman-bd
  pod 'Alamofire', '~> 4.4'
  pod 'SOTabBar'
   pod 'NVActivityIndicatorView'
  pod 'IQKeyboardManagerSwift’ , '~> 6.2.0'
  pod 'SDWebImage', '~> 4.0'

  pod 'SwiftyJSON', '~> 4.0'

  target 'bellman-bdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bellman-bdUITests' do
    # Pods for testing
  end

end
